### ISSUE TITLE
how to visualise the target sequence instead of the outpt sequence

### ISSUE THREAD

**Issue by tangxiangru** [Neoanarika/torchexplainer#1]

**Comment by MLdoesML** [comment]
You can use the debug flag as shown here 
`python attribution.py -model trained.chkpt -data data/multi30k.atok.low.pt -out igs.pkl -no_cuda -debug`

**Comment by tangxiangru** [comment]
> You can use the debug flag as shown here
> `python attribution.py -model trained.chkpt -data data/multi30k.atok.low.pt -out igs.pkl -no_cuda -debug`

I have this bug
`[Info] Trained model state loaded.
Traceback (most recent call last):
File "attribution.py", line 218, in
IG,tgt_IG,src_seq,translated_sentence,tgt_trans_sent = dict_store["IG"],dict_store["tgt_IG"],dict_store["src_seq"],dict_store["translated_sentence"],dict_store["tgt_trans_sent"]
KeyError: 'tgt_IG'`

**Comment by tangxiangru** [comment]
> You can use the debug flag as shown here
> `python attribution.py -model trained.chkpt -data data/multi30k.atok.low.pt -out igs.pkl -no_cuda -debug`

thanks so much, and thank for your rapid reply
